language: android

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - development

android:
  components:
    - tools
    - build-tools-29.0.3
    - android-28
    - extra

jdk:
  - oraclejdk8

# script:
#    - ./gradlew clean jacocoTestReport coveralls
