language: android
dist: trusty

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - development

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-28
    - extra

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
   - ./gradlew clean build jacocoTestReport coveralls
